USE adventure_db;

INSERT INTO scenarios (scenario, choiceA, choiceB)
VALUES ("You wake up in your bedroom, it’s 8am you are hungry, hungry for a bagel.@A.go back to sleep,@B. Get out of bed and shower ",2,3),
 ("You’ve slept in too long! Your favorite bagel shop closes in 20 mins!@A.Hurry up, get dressed and try to get your bagel@B. Go to your second favorite bagel shop that’s open all day", 4, 5),
 ("You’re trying to choose a shirt to wear.@A. Put on your blue shirt@B. Put on your red shirt ",6,7),
 ("When you stand out of bed you are so fatigued from hunger that your legs give out and you hit your head on the corner of a table. You will not be getting a bagel today.@Better luck next time @Try again?", 1,1),
 ("Your second favorite bagel shop is a little further away, too far away to walk.@A.Take the bus@B. Drive your car", 8,9),
 ("You look fantastic in blue! Time to walk to the bagel shop, but your dog is in low spirits. Should you bring them with you?@A.Yes@B. No", 10,11),
 ("You’ve forgotten you live in Spain, today is the running of the bulls. Run for your life! You will not be getting your bagel today. @Better luck next time @Try again?", 1,1),
 ("Public transport is fun! You run into your friend Karl while en route. Karl is getting off two stops before you. Will you get off the bus with Karl or continue on to your destination before getting you bagel.@A. Walk with Karl@B. Stay till you get to your stop", 6,7),
 ("Your car has been infested by mild mannered raccoons! You will not be getting your bagel today.@Better luck next time @Try again?", 1,1),
 ("Your dog’s mood is immediately improved. You’re pretty happy too. You and your dog are so happy and cool that you're attracting A LOT of attention. A random lady asks to pet your if you’d like to get some avocado toast.@A. No lady!@B. Sure", 14,15),
 ("You being your lonely journey to obtain sustenance. With no one to keep you company you realize how hungry you actually are. There's a red light at the cross walk.@A. Just cross there aren’t any cars@B. You’ll wait like a good law abiding citizen ", 16,17),
 ("Karl is what your Mom would call a “bad egg” and suggests that the two of you politely ask the local bank for all their money.@A. You trust Karl, plus he asked nicely. You’ll accompany him to the bank@B. Mom’s usually right, and you’re very hungry.Bagels above all ", 18,19),
 ("You get off at your stop and make your way past the Dimsdale DimmaDome. Timmy Turner is looking around frantically for what calls his Fairy God Parents.@A. Laugh at weird boy@B. Help weird boy", 19,20),
 ("Dogs don’t even like avocados. Your dogs completely offended by this and wants to go home.@A. Continue on your path with your mad dog@B. Appease your dog and turn around.", 21,22),
 ("So it looks like you’re not getting a bagel today? I’m sorry but I don’t think you've read the directions. Please start over. @Better luck next time @Try again?", 1,1),
 ("Oh no! A police man has spotted you. By the look in his eye he really wants to give you a ticket for j walking.@A. Take the loss, maybe he’s a cool cop?@B. RUN", 23,24),
 ("While waiting at the crosswalk you fail to notice the piano being delivered via crane. You are squished by a piano, Wile E Coyote style. You will not be getting a bagel today@Better luck next time @Try again?", 1,1),
 ("The heat is on, what has started out as a chill morning has now resulted in you being arrested. There are zero bagels in this prison.@Better luck next time @Try again?", 1,1),
 ("You continue on your journey to the bagel shop. You get to the bagel shop but there are girl scouts selling cookies outside.@A. All girl scouts are scammers, ignore them and go inside@B. Buy some cookies before getting your bagel, you deserve it", 25,26),
 ("This weird boy is so thankful you helped him find his Fairy God Parents, Comso and Wanda, he asks you to make a wish and he’ll make it come true.@A. This kid is VERY weird and you do NOT think this is real. You continue on your way in a very expedited manor@B. You wish for an infinite amount of bagels", 27,28),
 ("The anger from your dog transfers into your consciousness. You begin to behave like a feral beast. The severity of you hunger only amplifies your ferocity.@A. Try eastern breathing methods in an effort to calm down@B. Embrace your inner beast", 29,30),
 ("There still aren’t any bagels at your house. You will not receive a bagel today.@Better luck next time @Try again?", 1,1),
 ("This was definitely not one of those “cool cops”. He has given you a $500 ticket for J walking, cleaning out your bank account. There is no way for you to get a bagel today.@Better luck next time @Try again?", 1,1),
 ("Cops do not like when you run from them. He begins to chase you. This has resulted in a full on police chase.@A. Run away to Mexico@B. Hide in a ditch", 31,32),
 ("All your patience today has paid off. Your wildest dream has finally come true… Congratulations you have received your bagel!@Good work!@Try Again? ", 1,1),
 ("This turns out to be a rouge troupe of girl scouts. They jump you and take all of your possessions. You are penniless and will not be getting a bagel today.@Better luck next time @Try again?", 1,1),
 ("Timmy is offended by this and wishes for you to never have a bagel again. You will not be getting a bagel today or ever again.@Better luck next time @Try again?", 1,1),
 ("The sky opens and an endless downpour of everything bagels covers the land. You are suffocated by your own greed and desires. You have succeeded in getting your bagel today, but at what cost? You expire under a mountain of everything bagels.@Better luck next time @Try again?", 1,1),
 ("The zen flows through you. All those yoga classes have been really paying off. Your dog is calm too and you hit a sick tree pose, giving you full mental clarity. You B-line to the bagel shop. You get your bagel today@Good work!@Try Again? ", 1,1),
 ("It’s too late, the transformation has begun. You forgot about you trip to Transylvania last week and that strange hairy man that bit you. You have been walking around confused for so long the moon has begun to shine. You transform into a werewolf and everyone in town is mad at you. You flee the city and will not be getting a bagel today.@Better luck next time @Try again?", 1,1),
 ("Bagels literally don’t exist in Mexico. You will not be getting a bagel today.@Better luck next time @Try again?", 1,1),
 ("As comfy as this ditch is it’s time to move. You make your way to the bagel shop where the police are waiting for you.@A. Give yourself up@B. Run home and forget about your bagel", 33,34),
 ("You have been taken away to Federal Prison. Society takes j walking VERY serious. Luckily they’re still serving breakfast, bagels infact. Congratulations you have received your bagel.@Good work!@Try Again? ", 1,1),
 ("You are a bagel-less coward.@Better luck next time @Try again?", 1,1);